name: CI
on:
  pull_request:
  push:


jobs:

  Backend_setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.4'

      - name: Install dependencies
        run: npm install
        working-directory: ./blog-backend

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./blog-backend
        continue-on-error: true
        
      - name: Run tests
        run: npm run test
        working-directory: ./blog-backend
        continue-on-error: true



  Mobile_setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.4'

      - name: Install dependencies
        run: npm install
        working-directory: ./blog-Mobile

      - name: Run ESLint
        run: npx eslint .
        working-directory: ./blog-Mobile

      - name: Run expo-check
        run: npx expo install --check || true
        working-directory: ./blog-Mobile

      - name: run expo-doctor
        run: npx expo-doctor || true
        working-directory: ./blog-Mobile
